micronaut:
  application:
    name: micronaut-jpa-demo

logging:
  level:
    io.micronaut: DEBUG

datasources:
  default:
    url: jdbc:mariadb://localhost:3310/db
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true    